### PR TITLE
Improve icon

### PR DESCRIPTION
**Pull request by studiosciences**
This replaces the app-icon.icns with an addition to the Asset Catalog.

### CODE REVIEW

**Comment by mipstian** [comment]
Cool, I tested this in Launchpad and Finder. Screenshot for reference:

screen shot 2015-09-30 at 6 25 26 pm

Here's all I can think of:
- drop shadow :)
- it weirdly looks like it's illuminated from the top left, instead of just straight up top like the others, which makes it look really different. I think the borders/base should basically be symmetric like in the Terminal icon.
- there's still a png of the old icon in the repo root, could you delete that in this PR? there's no reason for it to be there now that we're using an asset catalogue (awesome btw)
- could you make a folder "artwork" in the repo and commit the sketch file this comes from? so I can do the remaining tweaks and I can stop bothering you :) This will also allow me to export the icon in different sizes (for my website etc.)

**Comment by studiosciences** [comment]
OK, give it another look.

**Comment by mipstian** [comment]
Much better!

screen shot 2015-10-01 at 6 46 25 am

Let's merge this! I might do some more work on it though if you don't mind. I wanna try to replicate the effect in Apple's system icons and see if it works.

**Comment by studiosciences** [comment]
It's all good. 

I had been looking at this, particularly the lighting near the bottom:
http://martiancraft.com/blog/2014/07/inspecting-yosemite-icons/

I cooled the top borders and warmed the bottom border, but that could also be done to the fill.

Marc

**Pull request merged**
