### PR TITLE
Allow usage with generic RSS feeds

### PR DESCRIPTION
**Pull request by chrisballinger**
With some minor changes I was able to get it working with an existing generic RSS feed.

Cheers!

### CODE REVIEW

**Comment by mipstian** [comment]
If we want to go generic we should do it well though :) We should only show the "Launch ShowRSS" menu item if the user has a showrss feed configured, and rename the box in the preferences from "ShowRSS Feed" to just "Feed", in all localizations.

This would take us half of the way towards #4. Do you want to tackle this?

**Comment by chrisballinger** [comment]
Ya that shouldn't be too bad.

Btw it looks like it works fine with sandboxing enabled, any reasons not to enable it?

**Comment by mipstian** [comment]
See #36

**Comment by mipstian** [comment]
Wow, great job!

One nitpick: in `MenuController.swift`, could you have it subscribe to `Defaults.changedNotification` (and call `refreshMenuContents()`) as well? This is because semantically the reason it needs to refresh is the preferences change rather than the feed check happening.

Other than that, LGTM!

**Comment by chrisballinger** [comment]
@mipstian Oh yeah good catch, fixed. Cheers!

**Comment by mipstian** [comment]
Perfecto. Thanks @chrisballinger !

**Comment by mipstian** [comment]
I've put out a prerelease with your change, in case you want to run a signed, optimized build :) https://github.com/mipstian/catch/releases/tag/2.0-alpha4

**Comment by chrisballinger** [comment]
Awesome thank you!

**Pull request merged**
